#!/usr/bin/env php
<?php

/**
 * Generates a minimal apache config to serve a php file, or a directory
 * @author Lachlan Donald <lachlan@ljd.cc>
 */

if(in_array('--help', $argv))
{
	echo "usage: phpup [-f myfile.php] [-d dir]\n\n";
	echo " -f myfile.php  -  route all requests through file\n";
	echo " -d dir         -  use an alternate docroot\n";
	echo " -p port        -  use an alternate port, defaults to 8000\n";
	exit(1);
}

$user = posix_getpwuid(posix_geteuid());
$options = getopt("f:d:p:");
$dir = isset($options['d']) ? $options['d'] : getcwd();
$port = isset($options['p']) ? $options['p'] : 8000;

// ----------------------------
// env setups 

$apachedir = $dir.'/.apache';

printf(">> building local apache instance in %s\n", $dir);

if(is_dir($apachedir))
	`rm -rf $apachedir`;

mkdir($apachedir, 0700, true);

$config = <<<"APACHECONF"
ServerRoot $apachedir 
PidFile httpd.pid 
ScoreBoardFile httpd.scoreboard
LockFile accept.lock
HostnameLookups off
User {$user['name']} 
ServerSignature Off
UseCanonicalName Off
Timeout 50
KeepAlive On
MaxKeepAliveRequests 40
KeepAliveTimeout 5
ServerName phpup
StartServers 16
MinSpareServers 16
MaxSpareServers 32
ServerLimit 400
MaxClients 400
MaxRequestsPerChild 10000
Listen *:$port
DocumentRoot $dir 
LoadModule mime_module /usr/libexec/apache2/mod_mime.so
LoadModule php5_module /usr/libexec/apache2/libphp5.so 
LoadModule log_config_module /usr/libexec/apache2/mod_log_config.so
AddHandler php5-script .php 
LogFormat "%h %l %u %t \"%r\" %>s %b" common
CustomLog "access.log" common
ErrorLog "error.log"\n
APACHECONF;

if(isset($options['f']))
{
	$config .= <<<"REWRITECONF"
LoadModule rewrite_module /usr/libexec/apache2/mod_rewrite.so
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule .* /{$options['f']} [L,QSA]\n
REWRITECONF;
}

file_put_contents("$apachedir/apache.conf", $config);

printf(">> starting apache on port %d\n", $port);
$handle = popen("httpd -f apache.conf -d $apachedir -D FOREGROUND", "r");
printf(">> listening...\n");

sleep(2);
$accesslog = popen("tail -f $apachedir/access.log 2>&1", 'r');
while(!feof($accesslog)) 
	printf(fgets($accesslog));



